Fixed container-push multiple registry playbook
This patch fixes container-push multiple registry
playbook as target_registeries expects a list
containing all the resources related to registry,
This patch re-arranges back with proper list and
refactor the generate_list.sh script to avoid
the error during promotion with other registires.

Closes-Bug: #1923221
Change-Id: Id184246f877b47d0e8cb1624ec8da92f0fb68912

diff --git a/ci-scripts/container-push/roles/containers-promote/templates/generate_list.sh.j2 b/ci-scripts/container-push/roles/containers-promote/templates/generate_list.sh.j2
--- a/ci-scripts/container-push/roles/containers-promote/templates/generate_list.sh.j2
+++ b/ci-scripts/container-push/roles/containers-promote/templates/generate_list.sh.j2
@@ -4,11 +4,14 @@ c_list=(
 {% endfor %}
 )
 
+target_registry=[
 {% for registry in target_registries %}
-target_registry='{{ registry.host }}/{{ registry.namespace }}'
+'{{ registry.host }}/{{ registry.namespace }}'
 {% endfor %}
+]
 source_registry='{{ source_registry.host }}/{{ source_registry.namespace }}'
-
+use_quay={{ use_quay }}
+enable_downstream={{ enable_downstream }}
 
 LOG_HOME="{{- tmp_file_root -}}"
 
@@ -26,13 +29,20 @@ else
     registry=$source_registry
 fi
 
-for container in "${c_list[@]}"; do
-    echo "$container" >> $LOG_HOME/inspect_logs.txt
-    docker manifest inspect --insecure "$registry/$container:{{ full_hash }}" >> $LOG_HOME/inspect_logs.txt
-    res=$?
-    if [ $res -eq 0 ]; then
-        echo "$container" >> $containers_file
-    else
-        echo "$container" >> $missing_containers_file
-    fi
+for reg in "${registry[@]}"; do
+    for container in "${c_list[@]}"; do
+        echo "$container" >> $LOG_HOME/inspect_logs.txt
+        # As we are pushing the container to docker.io so adding the condition specifically for docker.io to avoid the failures while doing the promotion.
+        if [[ "$use_quay" == false && "$enable_downstream" == false && "$reg" == *"docker.io"* ]]; then
+            docker manifest inspect --insecure "$reg/$container:{{ full_hash }}" >> $LOG_HOME/inspect_logs.txt
+        else
+            docker manifest inspect --insecure "$reg/$container:{{ full_hash }}" >> $LOG_HOME/inspect_logs.txt
+        fi
+        res=$?
+        if [ $res -eq 0 ]; then
+            echo "$container" >> $containers_file
+        else
+            echo "$container" >> $missing_containers_file
+        fi
+    done
 done
