INFRA: Deploy cockpit on CS9
This change adds method to deploy existing cockpit VM
based on CS9.

* added configure_podman_environment role. It is replacement
  for setup_docker_compose role [1].
* added configure_cockpit role scoped to run on CS9,
  based on existing toolbox role [2].

[1]: https://github.com/rdo-infra/ci-config/blob/master/ci-scripts/infra-setup/roles/setup_docker_compose/tasks/main.yaml
[2]: https://github.com/rdo-infra/ci-config/blob/master/ci-scripts/infra-setup/roles/rrcockpit/tasks/main.yml

Change-Id: Iaa9cb4de5948ecb6b43393ce1c77ba9a0dfc1762

diff --git a/ci-scripts/infra-setup/roles/rrcockpit/files/telegraf_py3/Dockerfile b/ci-scripts/infra-setup/roles/rrcockpit/files/telegraf_py3/Dockerfile
--- a/ci-scripts/infra-setup/roles/rrcockpit/files/telegraf_py3/Dockerfile
+++ b/ci-scripts/infra-setup/roles/rrcockpit/files/telegraf_py3/Dockerfile
@@ -20,4 +20,11 @@ RUN mkdir -p /usr/local/bin/templates
 COPY templates/* /usr/local/bin/templates/
 RUN ln -s /usr/bin/python3 /usr/bin/python
 
+# NOTE(dasm): Install RHEL certs inside the container
+# If the command failed, ignore it by '|| true'
+RUN cd /etc/pki/ca-trust/source/anchors && \
+    curl -O https://password.corp.redhat.com/RH-IT-Root-CA.crt && \
+    curl -O https://password.corp.redhat.com/pki-ca-chain.crt && \
+    update-ca-trust extract && update-ca-trust enable || true
+
 CMD ["telegraf", "--debug", "--config-directory","/etc/telegraf/telegraf.d/","--input-filter", "exec"]
