Update grep for tripleo-common in dynamic container list
With the addition of tripleo-common tempest plugin, there are now
2 packages in tripleo-common in the name.

This patch updates the grep to get only the hash of the
openstack-tripleo-common package, and should be resilient to a
future package with tripleo-common in the name.

It also adds a check for the container list being empty and fails
the playbook in this case, since we do not want to proceed
promotion without containers pushed.

Change-Id: I6c8643aa47276049cc8621a94bb49a7168071ad2

diff --git a/ci-scripts/container-push/container-push.yml b/ci-scripts/container-push/container-push.yml
--- a/ci-scripts/container-push/container-push.yml
+++ b/ci-scripts/container-push/container-push.yml
@@ -34,7 +34,7 @@
 
     - name: Get the tripleo-common commit in the promoted hash
       shell: >
-        curl {{ dlrn_url }} | grep tripleo-common | cut -f3 -d','
+        curl {{ dlrn_url }} | grep ',openstack-tripleo-common-[0-9]' | cut -f3 -d','
       register: local_release
 
     - name: Set the release_url
@@ -54,6 +54,12 @@
                 echo "ERROR ========== centos-binary-$image IS NOT BUILT! FIX THIS ASAP! ==========";
             fi
         done
+        # fail the script and exit with error if the container list is empty
+        if [ ! -s {{ containers_file }} ]; then
+            echo "FAIL";
+            echo "ERROR =========== container list is empty THIS IS A CRITICAL BUG in the container push playbook";
+            exit 1
+        fi
 
     - name: run container tagging and always cleanup at the end
       block:
